# kind-config.yaml
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: my-cluster
nodes:
  # Control-plane (master)
  - role: control-plane
    extraPortMappings:
      # Map NodePort 30080 to EC2 host so you can access the app
      - containerPort: 30081
        hostPort: 8080
        protocol: TCP

  # Worker nodes
  - role: worker
  - role: worker
