apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-deployment
  labels:
    app: python-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: python-app
  template:
    metadata:
      labels:
        app: python-app
    spec:
      containers:
      - name: python-container
        image: python:3.11-slim
        command: ["python", "-m", "http.server", "8080"]
        ports:
        - containerPort: 8080
