apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-deployment
  namespace: python
  labels:
    app: python-app
spec:
  replicas: 3  # 👈 creates 2 pods
  selector:
    matchLabels:
      app: python-app
  template:
    metadata:
      labels:
        app: python-app
    spec:
      containers:
        - name: python-container
          image: python:3.10-alpine
          command: ["python", "-m", "http.server", "8080"]
          ports:
            - containerPort: 8080

~
