apiVersion: v1
kind: Service
metadata:
  namespace : python
  name: python-nodeport
spec:
  selector:
    app: python-http
  ports:
    - protocol: TCP
      port: 8080        # internal port
      targetPort: 8080  # container port
      nodePort: 30080   # port on the node you can access
  type: NodePort
