apiVersion: v1
kind: Service
metadata:
  name: python-service
spec:
  type: NodePort
  selector:
    app: python-app
  ports:
    - port: 8080         # Cluster-internal port
      targetPort: 8080   # Container port inside the Pod
      nodePort: 30081    # Port exposed on each worker node (and via kind extraPortMappings to EC2)
